### ISSUE TITLE
Add development instructions to the README

### ISSUE THREAD

**Issue by hantuzun** [neu-fi/orangekit#1]
This library should be easy to contribute to. For that, we need extensive documentation on how to set up the development environment as well.

The package.json specifies pnpm and has pnpm scripts. For that, the developers need to have pnpm.

**Comment by koybasimuhittin** [comment]
[rainbowkit's contribution guideline](https://github.com/rainbow-me/rainbowkit/blob/main/.github/CONTRIBUTING.md) can be inspried
